name: Build React App and Deploy to Netlify Standard Environments

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test and Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client
      run: npm ci

    - name: Test Client
      run: npm test -- --passWithNoTests

    - name: Build Client
      run: npm run build

    - name: Deploy to Dev
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        DEPLOYMENT_ALIAS: dev
      run: |
        npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --alias "$DEPLOYMENT_ALIAS"

  deploy_to_dev:
    name: Deploy To Dev Env
    environment: 
      name: dev
      url: 'https://dev--modest-thompson-8f6521.netlify.app'

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Netlify Dev Env
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOYMENT_ALIAS: dev
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --alias "$DEPLOYMENT_ALIAS"

  deploy_to_stage:
    name: Promote to Stage Env
    environment: 
      name: stage
      url: 'https://stage--modest-thompson-8f6521.netlify.app'

    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Netlify Stage Env
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOYMENT_ALIAS: stage
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --alias "$DEPLOYMENT_ALIAS"


  deploy_to_prod:
    name: Promote to Production
    environment:
      name: production
      url: 'https://modest-thompson-8f6521.netlify.app'

    runs-on: ubuntu-latest
    needs: deploy_to_stage
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Netlify Prod Env
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --prod
